let div=document.getElementById("box");
 div.style.width="300px";
 div.style.height="200px"
 div.style.backgroundColor="yellow"
 div.style.margin="20px";
 div.style.padding="10px";
 div.innerText="Hello,I am div!";
 div.style.color="blue"
 div.style.fontSize="18px"
 div.style.fontWeight="bold"
